import db from '../db';
import Resort from '../models/resort'

db.on('error', console.error.bind(console, 'connection error:'));

const main = async () => {

const resorts = [
    {
      resortName: "Alta Sierra at Shirley Meadows",
      region: "Central California",
      image: "https://www.snow-forecast.com/pistemaps/Shirley-Meadows_pistemap.jpg?1601557110",
      description: "Alta Sierra ski resort and terrain park is located in the Sequoia National Forest in the Greenhorn Mountains of California, approximately 50 miles east of Bakersfield",
      verticalRise: 600,
      baseElevation: 6491,
      summitElevation: 7091,
      numberOfTrails: 11,
      numberOfLifts: 3,
      ticketChild: 60,
      ticketYouth: "",
      ticketAdult: 70,
      ticketSenior: 60,
      nearbyResorts: "[Snow Summit Mountain Resort]",
      contactAddress: "56700 Rancheria Rd Wofford Heights, CA 93285",
      contactEmail: "contactus@altasierra.com",
      contactWebsite: "altasierra.com/v2"
    },
    {
      resortName: "Bear Valley",
      region: "Central California",
      image: "https://www.skiresort.info/typo3temp/assets/_processed_/58/88/8e/e4/7f8912b9a9.jpg",
      description: "Bear Valley is a four season resort located between Lake Tahoe and Yosemite in the Central Sierra Mountains. With such a large skiable area of 1,280 acres you will never lack terrain. Winter activities also include cross-country skiing, snowshoeing, snowboarding, snowmobiling, dog sledding and backcountry adventures.",
      verticalRise: 1900,
      baseElevation: 6600,
      summitElevation: 8500,
      numberOfTrails: 75,
      numberOfLifts: 10,
      ticketChild: 62,
      ticketYouth: 95,
      ticketAdult: 132,
      ticketSenior: 95,
      nearbyResorts: "[Dodge Ridge, Kirkwood Ski Resort]",
      contactAddress: "2280 State Route 207, Bear Valley , CA 95223",
      contactEmail: "fun@bearvalley.com",
      contactWebsite: "http://www.bearvalley.com/"
    },
    {
      resortName: "Big Bear Mountain",
      region: "Southern California",
      image: "https://snowjamshow.com/wp-content/uploads/2020/01/bear-mountain-trail-map-768x543.jpg",
      description: "This high elevation ski resort is located in Big Bear Lake, California in the San Bernardino Mountains. Lift tickets are also good for Snow Summit. Bear Mountainis a 200 acre winter playground offering over 100 features in it's terrain park.",
      verticalRise: 1665,
      baseElevation: 7140,
      summitElevation: 8805,
      numberOfTrails: 24,
      numberOfLifts: 12,
      ticketChild: 67,
      ticketYouth: 122,
      ticketAdult: 149,
      ticketSenior: 122,
      nearbyResorts: "[Snow Summit Mountain Resort, Snow Valley]",
      contactAddress: "43101 Goldmine Drive, Big Bear Lake , CA 92305",
      contactEmail: "info@bbmr.com",
      contactWebsite: "http://www.bigbearmountainresorts.com/"
    },
    {
      resortName: "Boreal Mountain Resort",
      region: "Lake Tahoe / North",
      image: "https://s3.onthesnow.com/images/trailmaps/lake-tahoe/boreal/20181118201945/large.jpg",
      description: "Boreal Mountain Resort is located 80 miles from Sacramento. There is night lighting & sound system on the mountain to enhance your ski and boarding fun.",
      verticalRise: 500,
      baseElevation: 7200,
      summitElevation: 7700,
      numberOfTrails: 34,
      numberOfLifts: 10,
      ticketChild: "",
      ticketYouth: 84,
      ticketAdult: 104,
      ticketSenior: "",
      nearbyResorts: "[Alpine Meadows, Donner Ski Ranch, Homewood Mountain Resort, Northstar-at-Tahoe, Soda Springs, Squaw Valley, Sugar Bowl, Tahoe Donner]",
      contactAddress: "19749 Boreal Ridge Road, Soda Springs , CA 95728",
      contactEmail: "borealinfo@borealski.com",
      contactWebsite: "http://www.skiboreal.com/winter/index.html"
    },
    {
      resortName: "Buckhorn Ski/Snowboard Club",
      region: "Southern California",
      image: "https://files.skimap.org/mksir7eib3gn3e287pn8meuqezpn",
      description: "Buckhorn is a backcountry resort for skiers, snowboarders and cross country skiers. It is a non-profit club operating in the San Gaberial Mountains, California. Members have all year access to the throwback to the 50's lodge which sleeps up to 40 people.",
      verticalRise: 680,
      baseElevation: 7203,
      summitElevation: 7903,
      numberOfTrails: 5,
      numberOfLifts: 2,
      ticketChild: "",
      ticketYouth: "",
      ticketAdult: "",
      ticketSenior: "",
      nearbyResorts: "[Mount Waterman]",
      contactAddress: "58.33 mile marker Angeles National Forest, Angeles Crest Hwy, Pearblossom, CA 93553",
      contactEmail: "contact@buckhornlodge.org",
      contactWebsite: "https://www.buckhornlodge.org/"
    },
    {
      resortName: "China Peak",
      region: "Central California",
      image: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_china-peak_n4756-149783-1_pan.jpg",
      description: "China Peak Mountain Resort is located 65 miles northeast of Fresno at scenic Huntington Lake in the Sierra National Forest.",
      verticalRise: 1679,
      baseElevation: 7030,
      summitElevation: 8709,
      numberOfTrails: 45,
      numberOfLifts: 11,
      ticketChild: 51,
      ticketYouth: 86,
      ticketAdult: 113,
      ticketSenior: 102,
      nearbyResorts: "",
      contactAddress: "59265 Highway 168, Lakeshore , CA 93634",
      contactEmail: "info@skichinapeak.com",
      contactWebsite: "http://www.skichinapeak.com/"
    },
    {
      resortName: "Dodge Ridge",
      region: "Central California",
      image: "https://skiliftblog.files.wordpress.com/2021/08/dodgeridge_trailmap_13-14-1.jpg?w=1024",
      description: "Dodge Ridge is located in Tuolumne County , California just 30 miles (48 km) east of Sonora, California off of Highway 108. There are five terrain parks from easy to advanced throughout the mountain, including the Stagecoach park, Rockys Road, the Competition park, the Progression park, and the Boarder Cross Course.",
      verticalRise: 1600,
      baseElevation: 6600,
      summitElevation: 8200,
      numberOfTrails: 67,
      numberOfLifts: 12,
      ticketChild: 29,
      ticketYouth: 39,
      ticketAdult: 109,
      ticketSenior: 79,
      nearbyResorts: "[Bear Valley]",
      contactAddress: "1 Dodge Ridge Road, Pinecrest , CA 95364",
      contactEmail: "info@dodgeridge.com",
      contactWebsite: "http://www.dodgeridge.com/"
    },
    {
      resortName: "Donner Ski Ranch",
      region: "Lake Tahoe / North",
      image: "https://images.squarespace-cdn.com/content/v1/581b7797cd0f68b05009ce5e/1481147312422-JFT055EOJPDI424B3KG8/DonnerSkiRanch_TrailMap?format=1000w",
      description: "Donner Ski Ranch is located on US Route 40 high atop Donner Summit, in Norden, California.",
      verticalRise: 750,
      baseElevation: 7031,
      summitElevation: 7781,
      numberOfTrails: 52,
      numberOfLifts: 8,
      ticketChild: 59,
      ticketYouth: 89,
      ticketAdult: 99,
      ticketSenior: 89,
      nearbyResorts: "[Alpine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Homewood Mountain Resort, Northstar-at-Tahoe, Soda Springs, Squaw Valley, Sugar Bowl, Tahoe Donner]",
      contactAddress: "19320 Donner Pass Road, Norden , CA 95724",
      contactEmail: "dsrinfo@donnerskiranch.com",
      contactWebsite: "http://www.donnerskiranch.com/"
    },
    {
      resortName: "Heavenly",
      region: "Lake Tahoe / North",
      image: "https://visitlaketahoe.com/wp-content/uploads/2020/11/heavenly-mountain-resort760x450.jpg",
      description: "Heavenly Ski Resort is located on the California-Nevada border in South Lake Tahoe. The resort has the largest snowmaking and grooming fleet on the West Coast. It features multiple terrain parks, 94 trails and a 3,500-foot vertical drop. Skiers and snowboarders can glide for miles, surrounded by the towering peaks of the Sierra, while overlooking Lake Tahoe, the high desserts of Nevada and the ranch lands of the Carson Valley.",
      verticalRise: 3500,
      baseElevation: 6255,
      summitElevation: 10067,
      numberOfTrails: 97,
      numberOfLifts: 28,
      ticketChild: 105,
      ticketYouth: 157,
      ticketAdult: 191,
      ticketSenior: 159,
      nearbyResorts: "Alpine Meadows, Homewood Mountain Resort, Kirkwood Ski Resort, Northsta-at-Tahoe, Sierra at Tahoe, Squaw Valley]",
      contactAddress: "3860 Saddle Road, South Lake Tahoe , CA 96150",
      contactEmail: "Heavenlyinfo@vailresorts..com",
      contactWebsite: "http://www.skiheavenly.com/"
    },
    {
      resortName: "Homewood Mountain resort",
      region: "Lake tahoe / North",
      image: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/36000/36726-Homewood-Mountain-Resort.jpg",
      description: "Homewood Mountain Resort is set on the west shore of California's Lake Tahoe just south of Tahoe City. Many of the runs have spectacular lake views. Homewood has two terrain parks also having stunning lake views and terrain for all levels of expertise, from beginners to future X Games competitors. Homewood is located about an hour from Reno, NV, and about two hours from Sacramento, CA.",
      verticalRise: 1650,
      baseElevation: 6230,
      summitElevation: 7880,
      numberOfTrails: 64,
      numberOfLifts: 8,
      ticketChild: 109,
      ticketYouth: 129,
      ticketAdult: 159,
      ticketSenior: 129,
      nearbyResorts: "[Alpine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Donner Ski Ranch, Heavenly, Northstar-at-Tahoe, Sierra at Tahoe, Soda Springs, Squaw Valley, Sugar Bowl, Tahoe Donner]",
      contactAddress: "5145 Westlake Blvd, Homewood , CA 96141",
      contactEmail: "guestservices@skihomewood.com",
      contactWebsite: "http://www.skihomewood.com/"
    },
    {
      resortName: "June Mountain",
      region: "Central California",
      image: "https://snowbrains.com/wp-content/uploads/2013/05/june_lake_road_no_boat_13.jpg",
      description: "This Northern California resort is located near June Lake, southeast of Yosemite National Park.It offers 2,500 vertical feet of tree-lined runs, and a world class terrain park. It's diverse terrain offers two summits. The resort also offers guided backcountry tours.",
      verticalRise: 2590,
      baseElevation: 7545,
      summitElevation: 10090,
      numberOfTrails: 35,
      numberOfLifts: 7,
      ticketChild: 114,
      ticketYouth: 139,
      ticketAdult: 114,
      ticketSenior: "",
      nearbyResorts: "[Mammoth]",
      contactAddress: "3819 Hwy 158, June Lake , CA 93529",
      contactEmail: "aross@mammothresorts.com",
      contactWebsite: "http://www.junemountain.com/"
    },
    {
      resortName: "Kirkwood Ski Resort",
      region: "Lake Tahoe / North",
      image: "https://localfreshies.com/wp-content/uploads/2017/02/kirkwood_Mar-11-9-10-40-AM-1024x768.jpg",
      description: "Kirkwood is consistently rated in the top 10 for snow, terrain challenge and variety. It is located 90 minutes from Reno/Tahoe International Airport.",
      verticalRise: 2000,
      baseElevation: 7800,
      summitElevation: 9800,
      numberOfTrails: 86,
      numberOfLifts: 15,
      ticketChild: 96,
      ticketYouth: 119,
      ticketAdult: 132,
      ticketSenior: 119,
      nearbyResorts: "[Heavenly, Sierra at Tahoe]",
      contactAddress: "1501 Kirkwood Meadows Drive, Kirkwood , CA 95646",
      contactEmail: "info@kirkwood.com",
      contactWebsite: "http://www.kirkwood.com/"
    },
    {
      resortName: "Mammoth",
      region: "Cental California",
      image: "https://mediaim.expedia.com/destination/1/5837d5801d885cc38cddd5b825ca3ed5.jpg",
      description: "Mammoth is located in Eastern California along the east side of the Sierra Nevada mountain range. It features 1,000's of acres of terrain and an altitude that keeps things white into summer making it one of the longest ski seasons in North America. The mountain is surrounded by the protected backdrop of Mt. Whitney and Yosemite National Park.",
      verticalRise: 3100,
      baseElevation: 7953,
      summitElevation: 11053,
      numberOfTrails: 150,
      numberOfLifts: 28,
      ticketChild: 94,
      ticketYouth: 163,
      ticketAdult: 209,
      ticketSenior: 171,
      nearbyResorts: "[June Mountain]",
      contactAddress: "10001 Minaret Road, Mammoth Lakes , CA 93546",
      contactEmail: "800MAMMOTH@mammothresorts.com",
      contactWebsite: "http://www.mammothmountain.com/"
    },
    {
      resortName: "Mount Baldy",
      region: "Southern California",
      image: "https://images.squarespace-cdn.com/content/5f5b750c2612de46c3a1cbe2/1640686296101-X4D2SOTXPMRQ5ASQIRK7/Mt+Baldy+High+Shot.jpeg?content-type=image%2Fjpeg",
      description: "Skiing in Southern California. 26 runs spanning 3 mountains covering 800 acres with 2,100 vertical ft. Wide open glades, tree runs, bowls, moguls, groomed runs, cornices & quarter pipes.",
      verticalRise: 2100,
      baseElevation: 6500,
      summitElevation: 8600,
      numberOfTrails: 26,
      numberOfLifts: 4,
      ticketChild: 23,
      ticketYouth: 29,
      ticketAdult: 63,
      ticketSenior: 29,
      nearbyResorts: "",
      contactAddress: "Mt Baldy Road, Mt Baldy , CA 91759",
      contactEmail: "contactus@mtbaldy.com",
      contactWebsite: "http://mtbaldyskilifts.com/"
    },
    {
      resortName: "Mount Shasta",
      region: "Lake Tahoe / North",
      image: "https://alpenglowexpeditions.com/wp-content/uploads/2021/04/IMG_4197-2.jpg",
      description: "A full serve ski resort featuring alpine, nordic skiing and snowboarding. Located in Northern California just off of Interstate 5. Ski and stay lift ticket packages at local establishments.",
      verticalRise: 1453,
      baseElevation: 5500,
      summitElevation: 6890,
      numberOfTrails: 32,
      numberOfLifts: 5,
      ticketChild: 29,
      ticketYouth: 54,
      ticketAdult: 74,
      ticketSenior: 59,
      nearbyResorts: "",
      contactAddress: "4500 Ski Park Hwy, McCloud , CA 96057",
      contactEmail: "thinksnow@skipark.com",
      contactWebsite: "https://www.skipark.com/"
    },
    {
      resortName: "Mount Waterman",
      region: "Southern Califonia",
      image: "http://www.mountainyahoos.com/SkiResorts/LA_SanGabrielMtns/MtWaterman/BeginnerLift_img_2622_1274x956.jpg",
      description: "Mt. Waterman is a day ski and snowboard area close to the Los Angeles basin.",
      verticalRise: 1030,
      baseElevation: 7000,
      summitElevation: 8030,
      numberOfTrails: 27,
      numberOfLifts: 3,
      ticketChild: 30,
      ticketYouth: 60,
      ticketAdult: 70,
      ticketSenior: 30,
      nearbyResorts: "",
      contactAddress: "CA-2, La Ca�ada Flintridge, CA 93553",
      contactEmail: "mtwaterman@outlook.com",
      contactWebsite: "http://www.mtwaterman.org/"
    },
    {
      resortName: "Mountain High Ski Area",
      region: "Southern California",
      image: "https://www.mthigh.com/site/connect/blog/authors/john_mccolly/east-resort-now-open/listing_picture_override/fullsize",
      description: "Mountain High Ski Resort is located just 75 minutes from Los Angeles and Orange County. The area consists of three separate mountains...Mountain High East, West, and North. It is usually the first resort to open for Southern California skiing and snowboarding each season and the only local area with night skiing seven nights-a-week.",
      verticalRise: 1600,
      baseElevation: 6600,
      summitElevation: 8200,
      numberOfTrails: 59,
      numberOfLifts: 14,
      ticketChild: 129,
      ticketYouth: 129,
      ticketAdult: 129,
      ticketSenior: 129,
      nearbyResorts: "[Snow Valley]",
      contactAddress: "24510 Highway 2, Wrightwood , CA 92397",
      contactEmail: "john@mthigh.com",
      contactWebsite: "http://www.mthigh.com/"
    },
    {
      resortName: "Northstar-at-Tahoe",
      region: "Lake Tahoe / North",
      image: "https://assets.vailresorts.com/-/media/northstar/products/brochure/the-mountain/about-the-mountain/trail-map/ns_trailmap_mapside_07nov2017_300dpi-(1).ashx",
      description: "Northstar offers an alpine village atmosphere for skiing and snowboarding at Lake Tahoe, California.",
      verticalRise: 2280,
      baseElevation: 6330,
      summitElevation: 8610,
      numberOfTrails: 97,
      numberOfLifts: 20,
      ticketChild: 117,
      ticketYouth: 163,
      ticketAdult: 199,
      ticketSenior: 163,
      nearbyResorts: "[Alphine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Donner Ski Ranch, Heavenly, Homewood Mountain Resort, Soda Spring, Squaw Valley, Sugar Bowl, Tahoe Donner]",
      contactAddress: "100 Northstar Drive, Truckee , CA 96161",
      contactEmail: "northstar@vailresorts.com",
      contactWebsite: "http://www.northstarattahoe.com/"
    },
    {
      resortName: "Palisades Tahoe",
      region: "Lake Tahoe / North",
      image: "https://files.skimap.org/4xh21mxexm0mnegvr1g9107svhlx.jpg",
      description: "Palisades Tahoe (previously know as Squaw Valley Ski Resort) is one of the largest ski areas in the United States and attracts visitors from all over the world. It's located in the Sierra Nevada in Olympic Valley. 4,000 skiable acres span across six mountain peaks with open bowls and shoots. The aerial cable car travels 2,000 vertical feet to High Camp at the summit where the views of Lake Tahoe are stunning.",
      verticalRise: 2850,
      baseElevation: 6200,
      summitElevation: 9050,
      numberOfTrails: 170,
      numberOfLifts: 29,
      ticketChild: 137,
      ticketYouth: 176,
      ticketAdult: 195,
      ticketSenior: 176,
      nearbyResorts: "[Alphine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Donner Ski Ranch, Heavenly, Homewood Mountain Resort, Northstar-at-Tahoe, Soda Spring, Sugar Bowl, Tahoe Donner]",
      contactAddress: "1960 Squaw Valley Road, Olympic Valley , CA 96146",
      contactEmail: "info@palisadestahoe.com",
      contactWebsite: "http://squawalpine.com/"
    },
    {
      resortName: "Sierra at Tahoe",
      region: "Lake Tahoe / North",
      image: "https://skiliftblog.files.wordpress.com/2021/10/sierra-at-tahoe-trail-map-1920_1080.jpg",
      description: "Sierra-at-Tahoe is located in Twin Bridges, California 12 miles west of South Lake Tahoe. It is known for being a family oriented resort with some of Lake Tahoe's best beginner terrain. Skiers and boarders can get amazing runs through old-growth trees.",
      verticalRise: 2212,
      baseElevation: 6640,
      summitElevation: 8852,
      numberOfTrails: 46,
      numberOfLifts: 14,
      ticketChild: 45,
      ticketYouth: 100,
      ticketAdult: 110,
      ticketSenior: 100,
      nearbyResorts: "[Heavenly, Homewood Mountain Resort]",
      contactAddress: "1111 Sierra at Tahoe Road, Twin Bridges , CA 95735",
      contactEmail: "sierra@sierraattahoe.com",
      contactWebsite: "http://www.sierraattahoe.com/"
    },
    {
      resortName: "Snow Summit Mountain Resort",
      region: "Southern California",
      image: "https://files.skimap.org/yjgh28cfisbwzibz92ay9koartaa.jpg",
      description: "Snow Summit's offers a wide variety of interconnecting runs for all ski levels. Located at Big Bear Lake, California. Check out videos, live web cams and pics of the day.",
      verticalRise: 1200,
      baseElevation: 7000,
      summitElevation: 8200,
      numberOfTrails: 31,
      numberOfLifts: 14,
      ticketChild: 67,
      ticketYouth: 122,
      ticketAdult: 149,
      ticketSenior: 122,
      nearbyResorts: "[Big Bear Mountain, Snow Valley]",
      contactAddress: "880 Summit Blvd, Big Bear Lake , CA 92315",
      contactEmail: "info@bbmr.com",
      contactWebsite: "http://www.snowsummit.com/"
    },
    {
      resortName: "Snow Valley",
      region: "Southern California",
      image: "https://skiliftblog.files.wordpress.com/2017/04/snowvalley-trailmap1.jpg",
      description: "Located in Southern California's San Bernardino Mountains, the resort is just minutes from Lake Arrowhead and Running Springs. The resort doesn't offer tubing but does have the Snow Play experience where you take a chairlift up and sled down designated slides.",
      verticalRise: 1041,
      baseElevation: 6800,
      summitElevation: 7841,
      numberOfTrails: 29,
      numberOfLifts: 12,
      ticketChild: 47,
      ticketYouth: 95,
      ticketAdult: 105,
      ticketSenior: 95,
      nearbyResorts: "[Big Bear Mountain, Mountain High Ski Area, Snow Summit Mountain Resort]",
      contactAddress: "35100 Highway 18, 5 miles east of Running Springs, Running Springs , CA 92382",
      contactEmail: "svinfo@snow-valley.com",
      contactWebsite: "http://www.snow-valley.com/index_english.html"
    },
    {
      resortName: "Soda Spring",
      region: "Lake Tahoe / North",
      image: "https://files.skimap.org/qno61epdy8hwv67u63kxj6vcosos.png",
      description: "Soda Springs is the longest running ski resort in California. The resort features Planet Kids, a dedicated snow play area for children 8 and under.",
      verticalRise: 550,
      baseElevation: 6750,
      summitElevation: 7300,
      numberOfTrails: 15,
      numberOfLifts: 4,
      ticketChild: 80,
      ticketYouth: 80,
      ticketAdult: 80,
      ticketSenior: 80,
      nearbyResorts: "[Alphine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Donner Ski Ranch, Homewood Mountain Resort, Northstar-at-Tahoe, Squaw Valley, Sugar Bowl, Tahoe Donner]",
      contactAddress: "10244 Soda Springs Road, Soda Springs , CA 95728",
      contactEmail: "info@skisodasprings.com",
      contactWebsite: "http://www.skisodasprings.com/"
    },
    {
      resortName: "Sugar Bowl",
      region: "Lake Tahoe / North",
      image: "https://files.skimap.org/hpe4jjub7o1v5n33x4opwu3wtyjh.jpg",
      description: "Sugar Bowl is located in Norden, California. The ski resort is 10 miles west of Truckee, CA, and 45 miles west of Reno on Interstate 80, making it the closest major resort to Sacramento. Sugar Bowl's backcountry tours are professionally guided and give people the chance to participate in educational seminars, telemark and steeps clinics, snowshoe hikes, and more.",
      verticalRise: 1500,
      baseElevation: 6883,
      summitElevation: 8383,
      numberOfTrails: 102,
      numberOfLifts: 13,
      ticketChild: 95,
      ticketYouth: 130,
      ticketAdult: 163,
      ticketSenior: 135,
      nearbyResorts: "[Alphine Meadows, Boreal Mountain Resort, Boreal Mountain Terrain Park, Donner Ski Ranch, Homewood Mountain Resort, Northstar-at-Tahoe, Soda Spring, Squaw Valley, Tahoe Donner]",
      contactAddress: "629 Sugar Bowl Road, Norden , CA 95724",
      contactEmail: "info@sugarbowl.com",
      contactWebsite: "http://www.skisugarbowl.com/"
    },
    {
      resortName: "Tahoe Donner",
      region: "Lake Tahoe / North",
      image: "https://files.skimap.org/bmte0ekxil92ftnf1two4sssv0df.png",
      description: "This is a small, friendly resort offering both alpine skiing and cross country skiing, located near Truckee, North Lake Tahoe, California.",
      verticalRise: 600,
      baseElevation: 6750,
      summitElevation: 7400,
      numberOfTrails: 15,
      numberOfLifts: 5,
      ticketChild: 55,
      ticketYouth: 75,
      ticketAdult: 90,
      ticketSenior: 55,
      nearbyResorts: "[Apine Meadows, Boreal Mountain Resort, Boreal Mountain Tereain Park, Donner Ski Ranch, Homewood Mountain Resort, Northstar-at-Tahoe, Soda Springs, Squaw Valley, Sugar Valley, Sugar Bowl]",
      contactAddress: "11603 Snowpeak Way, Truckee , CA 96161",
      contactEmail: "ski@tahoedonner.com",
      contactWebsite: "http://www.tahoedonner.com/"
    },
    {
      resortName: "Yosemite Ski & Snowboard Area",
      region: "Central California",
      image: "https://i.imgur.com/koOY7Ar.png",
      description: "California's original ski area, Yosemite Ski & Snowboard Area (previously known as Badger Pass), is a full-service ski resort offering ski and snowboard instruction, rental equipment, a ski shop, childcare, and a cafeteria and lounge. 85 percent of the slopes are devoted to beginner and intermediate levels. Guided backcountry ski tours through Yosemite are available.",
      verticalRise: 800,
      baseElevation: 7200,
      summitElevation: 8000,
      numberOfTrails: 10,
      numberOfLifts: 5,
      ticketChild: 35,
      ticketYouth: 62,
      ticketAdult: 62,
      ticketSenior: 62,
      nearbyResorts: "",
      contactAddress: "Glacier Point Road, Yosemite National Park , CA 95389",
      contactEmail: "smayer@delawarenorth.com",
      contactWebsite: "http://www.travelyosemite.com/winter/yosemite-ski-snowboard-area/"
    }
  ]
  await Resort.deleteMany({})
  await Resort.insertMany(resorts)
  console.log(`seeded resorts`)
}

const run = async () => {   
    await main()
    db.close()
}

run()
  